#!/bin/sh

### BEGIN INIT INFO
# Provides:          skysissdaemon
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: skysissdaemon
# Description:       skysiss daemon actions
### END INIT INFO

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting skysissdaemon "
    
    # example 1 - system service
    # /usr/bin/foobar --config /etc/foo.conf start

    # example 2 - run script as user
    # su --login mkaz --command "/home/mkaz/bin/my-script --cmd-args"
    
    su --login skysiss --command "/home/skysiss/run_all.sh"
    
    ;;
  stop)
    echo "Stopping skysissdaemon"
    
    # example 1
    # /usr/bin/foobar --config /etc/foo.conf stop
    su --login skysiss --command "/home/skysiss/stop_all.sh"
    ;;
  *)
    echo "Usage: /etc/init.d/skysissdaemon {start|stop}"
    exit 1
    ;;
esac

exit 0
